spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cjhmdb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: true
  devtools: 
    livereload:
      enabled: true
logging:  level:    org.springframework.web: error
    com.cjhm.board: debug    