spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cjhmdb
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  devtools: 
    livereload:
      enabled: true